spring:
  profiles:
    active: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/learn_db
    username: admin
    password: 123456
    #启动时需要初始化的建表语句
    schema: classpath:schema-mysql.sql
  sql:
    init:
      schema-locations: classpath:sql/init/createDB.sql

server:
  port: 8080

# 是否停用Knife4j文档
knife4j:
  production: false

# 日志配置
logging:
  level:
    root: info
---
spring:
  profiles:dev


---
spring:
  profiles:test


---
spring:
  profiles:prod

