# 应用名称
server:
  port: 8081

spring:
  application:
    name: userPg
  #初始化基本的配置项
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/learn_db
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  sql:
    #启动时需要初始化的建表语句
    init:
      username: admin
      password: 123456
      platform: pg
      schema-locations: classpath:sql/init/createDB-{{platform}}.sql
      mode: always
      separator: ;
