# 应用名称
server:
  port: 8081

spring:
  application:
    name: userPg
  profiles:
    active: testPg

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dreamkite.pg.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

logging:
  level:
    com.dreamkite.pg.dao: debug
  pattern:
    level: DEBUG

---

spring:
  config:
    activate:
      on-profile: test
  #初始化基本的配置项
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/learn_db
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  sql:
    #启动时需要初始化的建表语句
    init:
      username: admin
      password: 123456
      platform: pg
      schema-locations: classpath:sql/init/createDB-{{platform}}.sql
#      mode: always # 如果启动springboot要执行记得开启always， 关闭下面的never
      mode: NEVER
      separator: ;


