spring:
  #初始化基本的配置项
  datasource:
    url: jdbc:h2:mem:learn_db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: root
    password:
    driver-class-name: org.h2.Driver
  sql:
    #启动时需要初始化的建表语句
    init:
      username: root
      password:
      platform: pg
      schema-locations: classpath:sql/init/createDB-{{platform}}.sql
      #      mode: always # 如果启动springboot要执行记得开启always， 关闭下面的never
      mode: always
      separator: ;
      data-locations: classpath:sql/init/h2/data-{{platform}}.sql