spring:
  profiles:
    active: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

# 是否停用Knife4j文档, 开启打开链接： http://localhost:8080/doc.html#/home
knife4j:
  production: false

# 日志配置
logging:
  level:
    root: info
---
spring:
  profiles:dev


---
spring:
  profiles:test


---
spring:
  profiles:prod

