spring:
  application:
    name: demo
  profiles:
    active: test
    group:
      test: testdb
      dev: devdb
      prod: proddb
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

# 是否停用Knife4j文档, 开启打开链接： http://localhost:8080/doc.html#/home
knife4j:
  production: false

# 日志配置
logging:
  level:
    root: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dreamkite.demo.model.entity
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

---
spring:
  profiles: dev


---
spring:
  profiles: test


---
spring:
  profiles: prod

