# 应用名称
spring:
  application:
    name: myeureka

server:
  port: 8761

#其中fetch-registry和register-with-eureka两个配置用来关闭Eureka的客户端行为。
#fetch-registry：表示是否从eureka server获取注册表信息，如果是单一节点，不需要同步其他eureka server节点，则可以设置为false；若是集群，则设置为true，默认为true。
#register-with-eureka：表示是否将自己注册到eureka server，默认为true。
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
